version: '3.8'

services:
  app_green:
    platform: linux/amd64        # 추가: 강제로 AMD64 사용
    image: jonneedev/study-0.0.1-snapshot.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8888:8888"
    networks:
      - jonnee-network

  app_blue:
    platform: linux/amd64        # 추가: 강제로 AMD64 사용
    image: jonneedev/study-0.0.1-snapshot.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8889:8888"
    networks:
      - jonnee-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - jonnee-network

networks:
  jonnee-network:
    external: true
