version: '3.8'

services:
  app_green:
    image: jonneedev/study-0.0.1-snapshot.jar
    environment:
      # MySQL 연결 시 network alias를 사용
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8888:8888"   # 현재 운영 중인 버전
    networks:
      - jonnee-network

  app_blue:
    image: jonneedev/study-0.0.1-snapshot.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8889:8888"   # 새롭게 배포할 버전 (내부 포트 8888을 외부에 8889로 노출)
    networks:
      - jonnee-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - jonnee-network

networks:
  jonnee-network:
    external: true
