spring:
  datasource:
    url: jdbc:mysql://mysql-test:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 자동 테이블 생성
    show-sql: true      # 실행되는 SQL 출력

server:
  port: 8888
